---
fail_fast: false
ci:
  skip:
    # The dependencies can't be installed on pre-commit.ci, but this runs in
    # the normal GitHub Actions workflow.
    - sort-regressionfiles-yaml
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
        exclude: |
          (?x)(
              ^ADF|
              ^DALTON|
              ^FChk|
              ^GAMESS|
              ^GAMESSDAT|
              ^GAMESS-UK|
              ^Gaussian|
              ^io|
              ^Jaguar|
              ^Molcas|
              ^Molpro|
              ^MOPAC|
              ^NBO|
              ^NWChem|
              ^ORCA|
              ^Psi3|
              ^Psi4|
              ^QChem|
              ^Turbomole|
              ^XTB
          )
  - repo: local
    hooks:
      - id: sort-regressionfiles-yaml
        name: Sort regressionfiles.yaml
        entry: ./sort_regressionfiles_yaml.sh
        language: script
        files: ^regressionfiles\.yaml$
  - repo: https://github.com/rhysd/actionlint
    rev: "v1.7.7"
    hooks:
      - id: actionlint
        additional_dependencies:
          - "github.com/wasilibs/go-shellcheck/cmd/shellcheck@v0.10.0"
