---
name: ci

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

permissions: {}

jobs:
  prechecks:
    uses: ./.github/workflows/pre-commit.yml
  nix:
    uses: ./.github/workflows/nix.yml
  all:
    needs: [prechecks, nix]
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: "true"
