---
name: build and test nix package

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: nix-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

permissions: {}

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      # Install Nix on the runner
      - uses: cachix/install-nix-action@cebd211ec2008b83bda8fb0b21c3c072f004fe04 # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      # Pull from the cachix cache
      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: cclib
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      # Checkout of the current head in the working dir
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: Check nix flake
        run: nix flake check -L
