---
name: pre-commit

# yamllint disable-line rule:truthy
on:
  workflow_call:

concurrency:
  group: style-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
      - run: |
          python -m pip install 'ruamel.yaml'
          if ! python sort_regressionfiles_yaml.py > regressionfiles.diff; then
              echo "difference found:"
              cat regressionfiles.diff
              if ! patch -p1 -i regressionfiles.diff regressionfiles.yaml; then
                  echo "patch didn't apply cleanly"
              else
                  echo "patch applied cleanly"
              fi
              exit 1
          fi
